-- Games

CREATE TABLE game (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  info_link VARCHAR(255)
);

CREATE TABLE platform (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  release_date TIMESTAMP WITH TIME ZONE
);

CREATE TABLE game_platform (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  game_id BIGINT,
  platform_id BIGINT NOT NULL
);
ALTER TABLE game_platform ADD CONSTRAINT FK_GAME_PLATFORM_ON_GAME FOREIGN KEY (game_id) REFERENCES game (id);
ALTER TABLE game_platform ADD CONSTRAINT FK_GAME_PLATFORM_ON_PLATFORM FOREIGN KEY (platform_id) REFERENCES platform (id);

CREATE TABLE collected_game_platform (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  collection_date TIMESTAMP WITH TIME ZONE NOT NULL,
  status VARCHAR(255),
  spent_time INTERVAL SECOND(8),
  comment VARCHAR(1023),
  game_platform_id BIGINT
);
ALTER TABLE collected_game_platform ADD CONSTRAINT FK_COLLECTED_GAME_PLATFORM_ON_GAME_PLATFORM FOREIGN KEY (game_platform_id) REFERENCES game_platform (id);

-- Effects

CREATE SEQUENCE modifier_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE effect (
  id BIGINT DEFAULT NEXT VALUE FOR modifier_seq NOT NULL PRIMARY KEY,
  name VARCHAR(255),
  description VARCHAR(1023),
  type VARCHAR(255)
);

CREATE TABLE collected_effect (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  effect_id BIGINT
);
ALTER TABLE collected_effect ADD CONSTRAINT FK_COLLECTED_EFFECT_ON_EFFECT FOREIGN KEY (effect_id) REFERENCES effect (id);

-- Items

CREATE TABLE item (
  id BIGINT DEFAULT NEXT VALUE FOR modifier_seq NOT NULL PRIMARY KEY,
  name VARCHAR(255),
  description VARCHAR(1023)
);

CREATE TABLE collected_item (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  item_id BIGINT
);
ALTER TABLE collected_item ADD CONSTRAINT FK_COLLECTED_ITEM_ON_ITEM FOREIGN KEY (item_id) REFERENCES item (id);
